index:
  path: /
  controller: App\Controller\TryStuffController::index

# ----------------- LyNX
lynx_new_link:
  path: /lynx
  controller: App\Controller\LynxController::new_link

lynx_show_links:
  path: /lynx/show
  controller: App\Controller\LynxController::show_links